'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace System.Web.Mvc

    Partial Public Class ViewMasterPage

        '''<summary>
        '''Head1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''TitleContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''CSSContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''BreadcrumbContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BreadcrumbContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''MainContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''FooterContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''ScriptsSection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptsSection As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
